media: assets
content:
  - name: posts
    label: Posts
    type: collection
    path: 'content/posts'
    filename: '{primary}.md'
    view:
      fields: 
        - title
        - date
        - tags
        - summary
        - draft
    exclude:
      - _index.md
    fields:
      - name: date
        label: Date
        type: date
        format: yyyy-MM-dd
      - name: draft
        label: Draft
        type: boolean
        default: true
      - name: title
        label: Title
        type: string
      - name: summary
        label: Summary
        type: string
      - name: tags
        label: Tags
        type: string
        list: true
      - name: body
        label: Body
        type: rich-text