media: assets
content:
  - name: posts
    label: Posts
    type: collection
    path: 'content/posts'
    view:
      fields: [ title, draft, date, summary ]
    fields:
      - name: date
        label: Date
        type: date
        format: yyyy-MM-dd
      - name: draft
        label: Draft
        type: boolean
        default: true
      - name: title
        label: Title
        type: string
      - name: summary
        label: Summary
        type: string
      - name: tags
        label: Tags
        type: string
        list: true
      - name: body
        label: Body
        type: rich-text