settings:
  content:
    merge: true
media: static
content:
  - name: home
    label: Home Page
    type: file
    path: "content/_index.md"
    fields:
      - name: title
        label: Title
        type: string
      - name: body
        label: Body
        type: text
        rows: 60
  - name: about
    label: About Page
    type: file
    path: "content/about.md"
    fields:
      - name: title
        label: Title
        type: string
      - name: body
        label: Body
        type: text
        options:
          rows: 60
      - name: draft
        label: Draft
        type: boolean
        default: true
  - name: posts
    label: Posts
    type: collection
    path: 'content/posts'
    filename: '{primary}.md'
    view:
      fields:
        - title
        - date
        - summary
        - draft
    exclude:
      - _index.md
    fields:
      - name: date
        label: Date
        type: date
        options:
          format: yyyy-MM-dd HH:mm:ss
          time: true
      - name: title
        label: Title
        type: string
      - name: slug
        label: Slug
        type: string
      - name: summary
        label: Summary
        type: string
      - name: body
        label: Body
        type: text
        options:
          autoresize: false
          rows: 10
      - name: draft
        label: Draft
        type: boolean
        default: true
      - name: tags
        label: Tags
        type: string
        list: true
      - name: categories
        label: Categories
        type: string
        list: true