media: assets
content:
  - name: home
    label: Home Page
    type: file
    path: "content/_index.md"
    fields:
      - name: title
        label: Title
        type: string
      - name: body
        label: Body
        type: text
  - name: about
    label: About Page
    type: file
    path: "content/about.md"
    fields:
      - name: title
        label: Title
        type: string
      - name: body
        label: Body
        type: text
      - name: draft
        label: Draft
        type: boolean
        default: true
      - name: menu
        label: Show in sidebar
        type: boolean
        default: true
  - name: posts
    label: Posts
    type: collection
    path: 'content/posts'
    filename: '{primary}.md'
    view:
      fields: 
        - title
        - date
        - tags
        - summary
        - draft
    exclude:
      - _index.md
    fields:
      - name: date
        label: Date
        type: date
        format: yyyy-MM-dd
      - name: title
        label: Title
        type: string
      - name: summary
        label: Summary
        type: string
      - name: body
        label: Body
        type: text
        rows: 40
      - name: draft
        label: Draft
        type: boolean
        default: true
      - name: tags
        label: Tags
        type: string
        list: true