---
aboutPage: true
author: ronanchilvers
authorTwitter: ronanchilvers
baseurl: /
collections:
  posts:
    output: true
    title: Posts
  uploads:
    output: true
    title: Uploads
defaults:
  -
    scope:
      path: ""
      type: pages
    values:
      footer: true
      layout: default
  -
    scope:
      path: ""
      type: posts
    values:
      footer: true
      layout: post
  -
    scope:
      path: ""
      type: drafts
    values:
      footer: true
      layout: post
description: "Stuff I thought of"
disqus: true
disqus_shortname: ronanchilvers-github-io
domain_name: "https://ronanchilvers.github.io"
environment: production
exclude:
  - Gemfile
  - Gemfile.lock
facebook_pixel: false
gems:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-seo-tag
google_analytics: UA-88193273-1
highlighter: rouge
logo: /assets/images/avatar@2x.png
markdown: kramdown
meta_description: "Stuff I thought of"
name: twaddle
paginate: 20
permalink: "/:year/:title.html"
sass:
  sass_dir: _resources/sass
timezone: UTC
title: ronanchilvers.github.io
twitter:
  username: ronanchilvers
url: "https://ronanchilvers.github.io"
