# Site settings
title: TheLittleDot
baseurl: ""
url: "http://thelittledot.com"
email: hallo@thelittledot.com
twitter: ronanchilvers
github:  ronanchilvers
rss: ronanchilvers

# Build settings
markdown: kramdown

# Defaults
defaults:
  -
    scope:
        path: ""
    values:
        layout: "default"
  -
    scope:
        path: ""
        type: "posts"
    values:
        layout: "post"
