# Site settings
title: bitconkers
baseurl: ""
url: "http://bitconkers.net"
email: hallo@bitconkers.net
twitter: ronanchilvers
github:  ronanchilvers
rss: true

# Build settings
markdown: kramdown

# Defaults
defaults:
  -
    scope:
        path: ""
    values:
        layout: "default"
  -
    scope:
        path: ""
        type: "posts"
    values:
        layout: "post"
